# Generated by Django 5.1.1 on 2024-10-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopick", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="product",
        ),
    ]
