# Generated by Django 5.1.1 on 2024-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopick", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
