# Generated by Django 5.1.1 on 2024-10-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopick", "0002_profile_postal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="postal_code",
        ),
    ]
